# ASWANTH K

## DATA ANALYTICS INTERNSHIP

### TASK 3 – Data Cleaning

***OASIS INFOBYTE***

# **Data Cleaning Project**
## **Load Dataset**
The dataset is loaded into pandas for inspection and cleaning.

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# **Dataset Overview**
Inspect the structure, columns, data types and number of records.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.shape

(891, 12)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# **Data Quality Report**
Check for:

Missing values

Duplicate rows

Data type issues

In [6]:
# Missing values

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
# Duplicate rows
df.duplicated ().sum()

np.int64(0)

In [8]:
# Summary statistics
df.describe (include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# **Handle Missing Values**
The dataset contains missing values in the following columns:

*AGE- 177 ,FILL WITH MEDIAN

*CABIN-687, DROP OR FILL UNKNOWN

*EMBARKED-2- FILL WITH MODE

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [10]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [11]:
df = df.drop('Cabin', axis=1)

In [15]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

# **Duplicated Rows**
The dataset contains no duplicate rows, so no records were removed.

In [12]:
df.duplicated().sum()

np.int64(0)

# **Verify Data Types**
Ensure that each column has the appropriate data type after cleaning.

In [13]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

# **Outlier Detection**
The Interquartile Range (IQR) method is used to identify outliers in the Fare column.

In [14]:
Q1 = df ["Fare"]. quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Fare"] < lower) | (df["Fare"] > upper)]
print("Number of outliers:", len(outliers))

Number of outliers: 116

# **Before vs After Summary**
The table below summarises the data quality improvements made during the cleaning proce

In [16]:
summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Before": [
        891,
        12,
        866, # Age (177) + embarked(2) + Cabin (687)
        0
    ],
    "After": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})
summary

           Metric  Before  After
0            Rows     891    891
1         Columns      12     11
2  Missing Values     866      0
3  Duplicate Rows       0      0

# **Save Cleaned Dataset**

In [17]:

df.to_csv("cleaned_tested.csv", index=False)

# **Conclusion**
The dataset was successfully cleaned by handling missing values, removing the highly incomplete Cabin column, verifying duplicate records, checking data types and detecting outliers. The cleaned dataset is now consistent , complete and suitable for further exploratory data analysis or machine learning tasks. Proper data cleaning improves data quality and ensures the future analyses produce reliable and meaningful insights.